# Generated by Django 5.0.11 on 2025-02-25 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deteccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_modelo', models.CharField(choices=[('yolo', 'YOLO'), ('claude', 'Claude API')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='detecciones/')),
                ('resultados_json', models.TextField()),
                ('numero_objetos', models.IntegerField(default=0)),
                ('tiempo_procesamiento', models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True)),
            ],
            options={
                'verbose_name': 'Detección',
                'verbose_name_plural': 'Detecciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
