# Generated by Django 5.0.11 on 2025-03-12 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_center_options'),
        ('deteccion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deteccion',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detecciones', to='center.center'),
        ),
    ]
