# Generated by Django 5.0.11 on 2025-03-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_app', '0002_deteccion_center'),
        ('uploads', '0004_image_created_at_image_created_by_image_optional_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deteccion',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detecciones', to='uploads.image'),
        ),
    ]
