# Generated by Django 5.0.11 on 2025-03-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_app', '0003_deteccion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deteccion',
            name='tipo_modelo',
            field=models.CharField(choices=[('yolo', 'YOLO'), ('cl', 'YOLO 2.0')], max_length=20),
        ),
    ]
