# Generated by Django 5.0.11 on 2025-04-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_app', '0004_alter_deteccion_tipo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deteccion',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha confirmado los resultados'),
        ),
    ]
