# Generated by Django 5.0.11 on 2025-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion_app', '0005_deteccion_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deteccion',
            name='tipo_modelo',
            field=models.CharField(choices=[('yolo', 'YOLO'), ('cl', 'YOLO 2.0'), ('rf_detr', 'RF_DETR')], max_length=20),
        ),
    ]
