# Generated by Django 5.0.11 on 2025-01-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'Centro de Acopio', 'verbose_name_plural': 'Centros de Acopio'},
        ),
    ]
