# Generated by Django 5.0.11 on 2025-01-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
    ]
