# Generated by Django 5.0.11 on 2025-02-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_image_options'),
    ]

    operations = [
    ]
