# Generated by Django 5.0.11 on 2025-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='categories_list',
            field=models.TextField(blank=True, help_text='Comma-separated list of category names'),
        ),
    ]
