# Generated by Django 5.0.11 on 2025-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_analyticsreport_categories_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptiondatapoint',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
